# Generated by Django 3.2.8 on 2023-01-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='password',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
