# Generated by Django 3.2.8 on 2023-01-21 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_contact_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_list',
            field=models.ManyToManyField(blank=True, related_name='_accounts_user_contact_list_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
