# Generated by Django 3.2.8 on 2023-01-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_contact_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_list',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_list',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
