# Generated by Django 3.2.8 on 2023-01-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_group_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_extension',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
